student_sys/student/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

student_sys/student_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('student.urls')),
    path('admin/', admin.site.urls),
]

student_sys/student/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.

class Student(models.Model):
    SEX_ITEMS = [
        (1, '男'),
        (2, '女'),
        (3, '未知')
    ]
    STATUS_ITEMS = [
        (0, '申请'),
        (1, '通过'),
        (2, '拒绝')
    ]

    name = models.CharField(max_length=128, verbose_name="姓名")
    sex = models.IntegerField(choices=SEX_ITEMS, verbose_name="性别")
    profession = models.CharField(max_length=128, verbose_name="职业")
    email = models.EmailField(verbose_name="邮箱")
    qq = models.CharField(max_length=128, verbose_name="QQ")
    phone = models.CharField(max_length=128, verbose_name="电话")

    status = models.IntegerField(choices=STATUS_ITEMS, verbose_name="审核状态", default=0)

    created_time = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="创建时间")

    def __str__(self):
        return f'Student: {self.name}'

    @classmethod
    def get_all(cls):
        return cls.objects.all()


class Meta:
    verbose_name = verbose_name_plural = "学员信息"

student_sys/student/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    def clean_qq(self):
        cleaned_data = self.cleaned_data['qq']
        if not cleaned_data.isdigit():
            raise forms.ValidationError('必须是纯数字')
        return int(cleaned_data)

    class Meta:
        model = Student
        fields = (
            'name', 'sex', 'profession',
            'email', 'qq', 'phone'
        )

student_sys/student/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import StudentForm
from .models import Student


# Create your views here.

def index(request):
    students = Student.get_all()
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = StudentForm()

    context = {
        'students': students,
        'form': form
    }
    return render(request, 'index.html', context=context)

student_sys/student/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学员管理系统</title>
</head>
<body>
<h3><a href="/admin/">Admin</a></h3>
<ul>
    {% for student in students %}
        <li>{{ student.name }} - {{ student.get_sex_display }} - {{ student.qq }} - {{ student.phone }} - {{ student.email }} -{{ student.profession }}
            - {{ student.created_time }} - {{ student.get_status_display }}</li>
        {% empty %}
        <li>没有学生</li>
    {% endfor %}
</ul>

<hr/>
<form action="/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit"/>
</form>
</body>
</html>